# Generated by Django 4.2.30 on 2026-07-18 10:48

import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)])),
                ('protein_g', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('carbs_g', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('fat_g', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('tags', models.JSONField(default=list)),
                ('eaten_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('ai', 'AI Quick-Add')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['eaten_at'], name='meals_meal_eaten_a_4eb214_idx'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='meals_meal_tags_27769b_gin')],
            },
        ),
    ]
